travis:
  secure:
    BINSTAR_TOKEN: Vlb5GiS72tu9h63cGjS648zP4f2+VZg/GMXMVTsH2pj86aX7wP/UmNtVykqZ0bLKmGFhOt4W4AS5uTkZaf0C6JZpZHweuCA7SYsDcag8siIgXfZ5MKtySCXRmj1JgKPiDqcntiyF3CUBve4Q6fElMS7dqhUzXKjr861ztbb2MA0IKOsQvX/008rDG23G/JNb4nnNoYECd2Dz5Bt07/s9SKN6tIm33ngQZMxGhQQIvuTSlaclsWAW6x3hicB7rixPTx0In8rf39aR5RW40uBHI3CYA2Q8V9+s8kXgnVvWdxK4j+YA1SzVQZl0/MTtT39JsFGMBRvfAgQpM8OWqVNKjaUe8sv+VqN2xuBRRVv0hlk5qccIgFAgjrYbq3rs2+yCulXO/Fr2ScSSbBRgaN3jZLTw60D3g66yg//XZAWlOsTCGFclTUPUJ7Vl2EqbKQnVpfzJGF/CKj+GUoQx/sTmsFAk4FOYSd/xcEDVRTXHesjtle4fDk1IXlJqRPt0hlobxto6q2hqhodEae3EioekPt093luiN0It1slneKvL3ZyocWJMyJLb3dt/KQVmIWtOxxytp0XOnz3Ps4EXFaFV8cRDi5Ng35ZL6fDYoxFwLriK8ANkHssODoUK4eDMkFJVI8pRZU5LVuuKGdrFdBzAIhur83kPFt2Utz6KUnCskn8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
