travis:
  secure:
    BINSTAR_TOKEN: i9E18z35/3naupCA2iU/jqosiGhXWY+xj8n3HSoYzK1TGn/Pz4x18KGdug1py2Y+FvM1u9Aj5mX4Ks6ojJigzkUXh6Vq9YRJqtSuUQ0aCCJ0ltz5EM1YBZsLgN0IAkdwsV8DnSmSPEKmprJX5Zt+SDdQiLQsKrF2lR3sWofEKY9Bu9YBvx1dTCiss3k1PwUE7881p0SgMf79YtcAdQr/Ig/kq7rTN4oXYRM/DnPSy8XnYnWcvIdGQgtuZmPQ6QJscm10Ct4iRPr1rqyS8I8Y0n1QA62Rkjt+gMHn9K70ORefN+EvNBVXnhTYhdVwV9ppi6B79F9/TPUvQYbaHgDQr71pgSpx5etWIxgtlgMT6CrPHw6MDBu9s3iNkZC+BAsTq2br1e3rRWnNLfLJCsmUUizhEiZbtCTBJaL8vXHpWB/Af6IueY8o1g9ns+GDlbYKxvQGuGFena7VUEDX/okii8nx7CgdphzUQM1PbMqjWSG1DLoSpVRAEXG4NpnSY6uxSTCdBYr9eS1xZzULWfRaUzgBK/WBHZOXyA8c7l9DWB0LfuxO171emJYnoTxRFOTSfDJQrx5LMm+lyhRidgWluCIlTE9vpHNnIqURwfGfkkj3JeSwPg0EbYb4OwkFLTAY1VBfUT7Bi9C0ADw14d/2Y9TZc8+Gf6gCJL9XRldtqHw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
